name: Main

on:
  push:
    branches:
      - main

jobs:
  run_tests:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'
          architecture: x64

      - name: Grant execute permission for gradlew
        run: |
          chmod +x gradlew

      - name: Run tests
        run: |
          ./gradlew clean test

  build_and_push:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: run_tests
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build, Push and Release a Docker container to Heroku.
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_DEV_APP_NAME }}
          usedocker: true

  draft_release:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    needs:
      - run_tests
      - build_and_push
    steps:

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: release-drafter/release-drafter@v5
        with:
          config-name: release-drafter.yaml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
