name: Dev

on:
  push:
    branches:
      - google-cloud
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE: ${{ github.repository }}

jobs:
  run_tests:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'
          architecture: x64

      - name: Grant execute permission for gradlew
        run: |
          chmod +x gradlew

      #- name: Run tests
      #  run: |
      #    ./gradlew clean test

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      #- name: Login to Github Packages
      #  uses: docker/login-action@v2
      #  with:
      #    registry: ${{ env.REGISTRY }}
      #    username: ${{ github.actor }}
      #    password: ${{ secrets.GITHUB_TOKEN }}

      #- name: Define image meta
      #  id: docker_meta
      #  uses: docker/metadata-action@v4
      #  with:
      #    images: ${{ env.REGISTRY }}/${{ env.IMAGE }}
      #    tags: |
      #      type=raw,value=sha-${{ github.sha }}
      #    labels: |
      #      org.opencontainers.image.authors=epoc
      #      org.opencontainers.image.vendor=three.consulting
      #    flavor: |
      #      latest=true

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@main
        with:
          project_id: epoc-auth-dev-361109
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Configure docker for GCP
        run: gcloud auth configure-docker

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: gcr.io/epoc-auth-dev-361109/epoc-backend-dev:latest

      # - name: Deploy to Cloud Run
      #  uses: google-github-actions/deploy-cloudrun@main
      #  with:
      #    image: gcr.io/epoc-auth-dev-361109/epoc-backend:latest
      #    service: <your-service-name>
      #    region: europe-north1
      #    platform: managed
      #    allow-unauthenticated: true
      #    env_vars: |
      #      FOO=bar
      #      ZIP=zap
