name: Pull Request

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

env:
  REGISTRY: ghcr.io
  IMAGE: ${{ github.repository }}

jobs:
  run_tests_and_build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'
          architecture: x64

      - name: Grant execute permission for gradlew
        run: |
          chmod +x gradlew

      - name: Run tests
        run: |
          ./gradlew clean test

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Define image meta
        id: docker_meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE }}
          tags: |
            type=raw,value=sha-${{ github.sha }}
          labels: |
            org.opencontainers.image.authors=epoc
            org.opencontainers.image.vendor=three.consulting
          flavor: |
            latest=true

      - name: Test building image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          no-cache: false
          push: false
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}

  automerge:
    needs: run_tests_and_build
    permissions:
      pull-requests: write
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 15
    if: github.actor == 'dependabot[bot]'
    steps:
      - name: Automerge dependabot PR
        uses: fastify/github-action-merge-dependabot@v3
        with:
          target: minor
          skip-commit-verification: true
