name: Pull Request

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  run_tests_and_build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:

    - name: Decrypt Firebase secret
      run: |
        cd firebase && gpg -q --batch --yes --decrypt-files --passphrase=${{ secrets.GPG }} *.gpg

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'zulu'
        architecture: x64

    - name: Grant execute permission for gradlew
      run: |
        chmod +x gradlew

    - name: Run tests
      run: |
        ./gradlew clean test

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Test building image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: Dockerfile
        no-cache: false
        push: false
        tags: ${{ steps.docker_meta.outputs.tags }}
        labels: ${{ steps.docker_meta.outputs.labels }}

